/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_mesos_Log_Entry */

#ifndef _Included_org_apache_mesos_Log_Entry
#define _Included_org_apache_mesos_Log_Entry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
