/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_mesos_Log_OperationFailedException */

#ifndef _Included_org_apache_mesos_Log_OperationFailedException
#define _Included_org_apache_mesos_Log_OperationFailedException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_mesos_Log_OperationFailedException_serialVersionUID
#define org_apache_mesos_Log_OperationFailedException_serialVersionUID -3042686055658047285LL
#undef org_apache_mesos_Log_OperationFailedException_serialVersionUID
#define org_apache_mesos_Log_OperationFailedException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
