/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_mesos_Log_Position */

#ifndef _Included_org_apache_mesos_Log_Position
#define _Included_org_apache_mesos_Log_Position
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
