#!/bin/bash

cd /root/nexus-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

for slave in $SLAVES; do
  echo "$slave: $@"
  ssh $SSH_OPTS $slave "$@"
done
